@startuml SpaceInvaders

' Clases principales
class Game {
    - Tabletop: Tabletop
    - PacFight: PacFight
    - PlayerHealth: PlayerHealth
    - EnemyManager: EnemyManager
    - EnemyMovementManager: EnemyMovementManager
    - EnemyHealthManager: EnemyHealthManager
    - EnemyShooter: EnemyShooter
    - Barrier: Barrier
    - Boss: Boss
}

class Tabletop {
    - EnemyManager: EnemyManager
    - EnemyMovementManager: EnemyMovementManager
    - EnemyHealthManager: EnemyHealthManager
    - EnemyShooter: EnemyShooter
    - Barrier: Barrier
    - Boss: Boss
    - PlayerHealth: PlayerHealth
}

class PacFight {
    - EnemyManager: EnemyManager
    - PlayerHealth: PlayerHealth
}

class EnemyManager
class EnemyMovementManager
class EnemyHealthManager
class EnemyShooter
class Barrier
class Boss
class PlayerHealth

class EnemySprite as "enemy.png"
class BossSprite as "boss.png"
class BarrierSprite as "barrier.png"
class BulletSprite as "bullet.png"

' Relaciones
Game --> Tabletop
Game --> PacFight
Game --> PlayerHealth
Game --> EnemyManager
Game --> EnemyMovementManager
Game --> EnemyHealthManager
Game --> EnemyShooter
Game --> Barrier
Game --> Boss

Tabletop --> EnemyManager
Tabletop --> EnemyMovementManager
Tabletop --> EnemyHealthManager
Tabletop --> EnemyShooter
Tabletop --> Barrier
Tabletop --> Boss
Tabletop --> PlayerHealth

PacFight --> EnemyManager
PacFight --> PlayerHealth

Player "1" *-- "1" PlayerHealth : utiliza
EnemyManager "1" *-- "*" EnemySprite : controla
Boss "1" *-- "1" BossSprite : utiliza
Barrier "1" *-- "1" BarrierSprite : utiliza
EnemyShooter "1" *-- "1" BulletSprite : utiliza

@enduml